-- DELETE FROM REVIEW WHERE writer_mid = 48;
-- delete from member where 

-- ON DELETE CASCADE 포함한 foreign key 재생성
-- 괄호가 있는 경우 괄호를 꼭 사용해야 합니다.
-- ALTER TABLE 자식_table_name 
-- ADD FOREIGN KEY (foreign_key_연결받을_자식_테이블의_column_name) 
-- REFERENCES 부모_table_name (foreign_key_로_가져올_column_name)
-- ON DELETE CASCADE;

-- 실제 사용 예제
-- ALTER TABLE order_items 
-- ADD FOREIGN KEY (item_id) 
-- REFERENCES orders (id)
-- ON DELETE CASCADE;

-- 제약 조건 조회
SELECT * FROM ALL_CONSTRAINTS WHERE TABLE_NAME = 'HEART' ;
SELECT * FROM ALL_CONSTRAINTS WHERE TABLE_NAME = 'REVIEW_IMAGE' ;
SELECT * FROM ALL_CONSTRAINTS WHERE TABLE_NAME = 'REVIEW_REPLY' ;
SELECT * FROM ALL_CONSTRAINTS WHERE TABLE_NAME = 'REVIEW_REPLY_COMMENT' ;
SELECT * FROM ALL_CONSTRAINTS WHERE TABLE_NAME = 'MEMBER' ;

-- REVIEW 파트
-- 제약 조건 삭제
ALTER TABLE HEART DROP CONSTRAINT FK93PKRRL33T00KMMCK1DQJLT12;
-- 제약 조건 추가
ALTER TABLE HEART ADD FOREIGN KEY (REVIEW_rno) REFERENCES REVIEW ON DELETE CASCADE;

-- 제약 조건 삭제
ALTER TABLE REVIEW_IMAGE DROP CONSTRAINT FK3D14AJJX02WVWY9NT3HAUY2AY;
-- 제약 조건 추가
ALTER TABLE REVIEW_IMAGE ADD FOREIGN KEY (REVIEW_rno) REFERENCES REVIEW ON DELETE CASCADE;

-- 제약 조건 삭제
ALTER TABLE REVIEW_REPLY DROP CONSTRAINT FKDISI6F33F4ADFHDHW9JQ8CHSI;
-- 제약 조건 추가
ALTER TABLE REVIEW_REPLY ADD FOREIGN KEY (REVIEW_rno) REFERENCES REVIEW ON DELETE CASCADE;
ALTER TABLE REVIEW_REPLY ADD FOREIGN KEY (REPLYER_MID) REFERENCES MEMBER;

-- 제약 조건 삭제
ALTER TABLE REVIEW_REPLY_COMMENT DROP CONSTRAINT FK82G69IE21IYV2845DOPOI8FOL;
ALTER TABLE REVIEW_REPLY_COMMENT DROP CONSTRAINT FK1LAX1DKXJW49IO6FYY3AH38QY;
ALTER TABLE REVIEW_REPLY_COMMENT DROP CONSTRAINT SYS_C0010519;

-- 제약 조건 추가
ALTER TABLE REVIEW_REPLY_COMMENT ADD FOREIGN KEY (REVIEW_rno) REFERENCES REVIEW ON DELETE CASCADE;
ALTER TABLE REVIEW_REPLY_COMMENT ADD FOREIGN KEY (REPLY_REPLY_no) REFERENCES REVIEW_REPLY ON DELETE CASCADE;
ALTER TABLE REVIEW_REPLY_COMMENT ADD FOREIGN KEY (REPLY_REPLY_no) REFERENCES REVIEW_REPLY ON DELETE SET NULL;



-- ANIMAL 파트
-- 제약 조건 삭제
ALTER TABLE ANIMAL_HEART DROP CONSTRAINT FKRQ4L7MKGK8VYXQYBNVRLKTIED;
-- 제약 조건 추가
ALTER TABLE ANIMAL_HEART ADD FOREIGN KEY (MEMBER_MID) REFERENCES MEMBER ON DELETE CASCADE;

-- 제약 조건 삭제
ALTER TABLE ANIMAL_REPLY DROP CONSTRAINT FK5C85N3339BM5OAADBFWUTB3RG;
-- 제약 조건 추가
ALTER TABLE ANIMAL_REPLY ADD FOREIGN KEY (MEMBER_MID) REFERENCES MEMBER ON DELETE CASCADE;

-- 제약 조건 삭제
ALTER TABLE ANIMAL_CART DROP CONSTRAINT FKQVROPCCPVTI2BKLBM4ND0OLGX;
-- 제약 조건 추가
ALTER TABLE ANIMAL_CART ADD FOREIGN KEY (MEMBER_MID) REFERENCES MEMBER ON DELETE CASCADE;

-- 제약 조건 삭제
ALTER TABLE ANIMAL_ITEM DROP CONSTRAINT FKEVVMS6VW9GP6C1D9EO8FECP4H;
-- 제약 조건 추가
ALTER TABLE ANIMAL_ITEM ADD FOREIGN KEY (ANIMAL_CART_CART_ID) REFERENCES ANIMAL_CART ON DELETE CASCADE;



-- MISSING 파트
-- 제약 조건 삭제
ALTER TABLE MISSING DROP CONSTRAINT FKILI0YBBAMCV4I9JBC82LNLR2N;
-- 제약 조건 추가
ALTER TABLE MISSING ADD FOREIGN KEY (MEMBER_MID) REFERENCES MEMBER ON DELETE CASCADE;

-- 제약 조건 삭제
ALTER TABLE MISSING_REPLY DROP CONSTRAINT FK89BWD5IN6GHRVH2KWNHSUWTUG;
-- 제약 조건 추가
ALTER TABLE MISSING_REPLY ADD FOREIGN KEY (MEMBER_MID) REFERENCES MEMBER ON DELETE CASCADE;

-- 제약 조건 삭제
ALTER TABLE MISSING_REPLY DROP CONSTRAINT FKSSRPI7XNXXI33XLIYX3M1OGOK;
-- 제약 조건 추가
ALTER TABLE MISSING_REPLY ADD FOREIGN KEY (MISSING_MISSNO) REFERENCES MISSING ON DELETE CASCADE;

-- 제약 조건 삭제
ALTER TABLE MISSINGIMAGE DROP CONSTRAINT FKQ79NLHHWFLT0PJDNTWUII7JFC;
-- 제약 조건 추가
ALTER TABLE MISSINGIMAGE ADD FOREIGN KEY (MISSING_MISSNO) REFERENCES MISSING ON DELETE CASCADE;

-- 제약 조건 조회
SELECT * FROM ALL_CONSTRAINTS WHERE TABLE_NAME = 'HEART' ;

-- ON DELETE CASCADE 포함한 foreign key 재생성
-- 괄호가 있는 경우 괄호를 꼭 사용해야 합니다.
-- ALTER TABLE 자식_table_name 
-- ADD FOREIGN KEY (foreign_key_연결받을_자식_테이블의_column_name) 
-- REFERENCES 부모_table_name (foreign_key_로_가져올_column_name)
-- ON DELETE CASCADE;

-- 제약 조건 삭제
ALTER TABLE HEART DROP CONSTRAINT FK93PKRRL33T00KMMCK1DQJLT12;
-- 제약 조건 추가
ALTER TABLE HEART ADD FOREIGN KEY (REVIEW_rno) REFERENCES REVIEW ON DELETE CASCADE;
































