-- scott 권한 부여
GRANT CONNECT, resource TO scott;
GRANT CREATE VIEW TO scott;


-- 데이터를 저장할 수 있는 저장공간 할당
ALTER USER SCOTT DEFAULT TABLESPACE USERS;
ALTER USER SCOTT TEMPORARY TABLESPACE TEMP;
ALTER USER SCOTT QUOTA 10M ON USERS;

alter session set "_oracle_script"=true;



-- DBA 권한을 가진 사용자만 사용자를 생성하고 권한 부여
-- SYSTEM, sys as sysdba

-- CREATE USER 아이디 IDENTIFIED BY 비밀번호;

-- TEST 생성
-- 공통 사용자 또는 롤 이름이 부적합합니다.(c##)
-- 21c XE 버전에서의 요구사항(다른버전은 다를수도 있음)
CREATE USER c##test IDENTIFIED BY test;

-- CREATE SESSION 권한을 가지고있지 않음 로그온이 거절
-- 권한 부여
-- SESSION, CREATE(USER, TABLE, SEQUENCE, VIEW...)
-- 권한 그룹 -> 롤(관련있는 권한들을 묶어놈)
-- CONNECT, RESOURCE
-- CONNECT(SESSION, CREATE TABLE, CREATE VIEW...)
-- RESOURCE(SEQUENCE, 프로시저, 테이블...)

-- GRANT 권한이름,.... TO 아이디
-- GRANT 롤이름,.... TO 아이디
GRANT CONNECT, RESOURCE TO c##test;

-- USER 생성 구문
-- 아이디,비번,권한,용량... 한줄로 쓴 구문
CREATE USER c##test2 IDENTIFIED BY test
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON USERS;
-- 유저에게 권한 부여
GRANT CONNECT, RESOURCE TO c##test2;

-- REVOKE 취소할 권한이름,... FROM 아이디

-- 비밀번호 변경
ALTER USER c##test2 IDENTIFIED BY test;

-- USER 생성
-- 아이디,비번,권한,용량...
CREATE USER c##jpauser IDENTIFIED BY 12345
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON USERS;
GRANT CONNECT, RESOURCE TO c##jpauser;

-- 연습 USER 생성
-- 아이디,비번,권한,용량...
CREATE USER c##jpahome IDENTIFIED BY 12345
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON USERS;

GRANT CONNECT, RESOURCE TO c##jpahome;

-- USER 생성
-- 아이디,비번,권한,용량...
CREATE USER c##guestbook IDENTIFIED BY 12345
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON USERS;

GRANT CONNECT, RESOURCE TO c##guestbook;

-- 연습 USER 생성
-- 아이디,비번,권한,용량...
CREATE USER c##guestbookhome IDENTIFIED BY 12345
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON USERS;

GRANT CONNECT, RESOURCE TO c##guestbookhome;

-- 오라클 연습 USER 생성
CREATE USER c##hr -- 아이디
IDENTIFIED BY 12345 -- 비밀번호
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON USERS; -- 용량
-- 권한 부여
GRANT CONNECT, RESOURCE TO c##hr;


-- 팀프로젝트 계정 생성
CREATE USER c##project1 -- 아이디
IDENTIFIED BY 1234 -- 비밀번호
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON USERS; -- 용량
-- 권한 부여
GRANT CONNECT, RESOURCE TO c##project1;


-- 팀프로젝트 DB 생성
CREATE USER c##project1db -- 아이디
IDENTIFIED BY 1234 -- 비밀번호
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON USERS; -- 용량
-- 권한 부여
GRANT CONNECT, RESOURCE TO c##project1db;


-- 개인프젝트 DB 생성
CREATE USER c##project2 -- 아이디
IDENTIFIED BY 1234 -- 비밀번호
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON USERS; -- 용량
-- 권한 부여
GRANT CONNECT, RESOURCE TO c##project2;




